name: Testing Skills
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment to environemnt
        required: true
        type: choice
        options:
          - dev
          - prod
          - qa
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: actions/checkout@v6
      - name: Print
        run: echo "welcome to Hello World"
