name: Testing Skills
on:
  workflow_dispatch: null
  workflow_inputs:
    inputs:
      environment:
        description: Deployment to environemnt
        require: true
        type: choice
        option:
          - dev
          - prod
          - qa
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: actions/checkout@v6
      - name: Print
        run: echo "welcome to Hello World"
